package penjualan_parfum.view;
import java.beans.PropertyVetoException;
import java.io.InputStream;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Vector;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
import penjualan_parfum.DBConnection;
import penjualan_parfum.entity.Barang;
import penjualan_parfum.entity.Pelanggan;
import penjualan_parfum.model.BarangModel;
import penjualan_parfum.model.PelangganModel;

public class MainMenu extends javax.swing.JFrame {
    
    private BarangForm barangForm;
    private PelangganForm pelangganForm;
    private PenjualanForm penjualanForm;
    private Connection connection;
    private BarangModel barangModel;
    private PelangganModel pelangganModel;
    private PenjualanLaporan penjualanLaporan;
    
    /** Creates new form MainMenu */
    public MainMenu() {
        initComponents();
        barangForm = new BarangForm(this, true);
        barangForm.setLocationRelativeTo(this);
        pelangganForm = new PelangganForm(this, true);
        pelangganForm.setLocationRelativeTo(this);
        penjualanForm = new PenjualanForm(); 
        this.setExtendedState(MAXIMIZED_BOTH);
        penjualanLaporan = new PenjualanLaporan(this, true);
        penjualanLaporan.setLocationRelativeTo(this);
        
        connection = DBConnection.newgetInstant();
        barangModel = new BarangModel(connection);
        pelangganModel = new PelangganModel(connection);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuPenjualan = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuBarang = new javax.swing.JMenuItem();
        menuPelanggan = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuBarangData = new javax.swing.JMenuItem();
        menuPelangganData = new javax.swing.JMenuItem();
        menuPenjualanData = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEM INFORMASI PENJUALAN");
        setName("MainMenu"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jDesktopPane1.setBackground(java.awt.SystemColor.activeCaption);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );

        jMenu1.setText("Transaksi");

        menuPenjualan.setText("Penjualan");
        menuPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPenjualanActionPerformed(evt);
            }
        });
        jMenu1.add(menuPenjualan);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Master");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        menuBarang.setText("Parfum");
        menuBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBarangActionPerformed(evt);
            }
        });
        jMenu2.add(menuBarang);

        menuPelanggan.setText("Pelanggan");
        menuPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPelangganActionPerformed(evt);
            }
        });
        jMenu2.add(menuPelanggan);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Laporan");

        menuBarangData.setText("Data Parfum");
        menuBarangData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBarangDataActionPerformed(evt);
            }
        });
        jMenu3.add(menuBarangData);

        menuPelangganData.setText("Data Pelanggan");
        menuPelangganData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPelangganDataActionPerformed(evt);
            }
        });
        jMenu3.add(menuPelangganData);

        menuPenjualanData.setText("Data Penjualan");
        menuPenjualanData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPenjualanDataActionPerformed(evt);
            }
        });
        jMenu3.add(menuPenjualanData);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jDesktopPane1.add(penjualanForm);
    }//GEN-LAST:event_formWindowOpened

    private void menuPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPenjualanActionPerformed
        // TODO add your handling code here:
        try{
            penjualanForm.show();
            penjualanForm.setSelected(true);
        } catch (PropertyVetoException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_menuPenjualanActionPerformed

    private void menuBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBarangActionPerformed
        // TODO add your handling code here:
        barangForm.show();
    }//GEN-LAST:event_menuBarangActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void menuPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPelangganActionPerformed
        pelangganForm.show();
    }//GEN-LAST:event_menuPelangganActionPerformed

    private void menuBarangDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBarangDataActionPerformed
        HashMap parameter = new HashMap();
        Vector<HashMap> data = new Vector<HashMap>();
        int no = 0;
        
        for(Barang barang : barangModel.getData()){
            HashMap row = new HashMap();
            row.put("kode", barang.getKode());
            row.put("nama", barang.getNama());
            row.put("satuan", barang.getSatuan());
            row.put("harga_satuan", barang.getHarga_satuan());
            row.put("no", ++no);
            data.add(row);
        }
        
        try{
            JRDataSource dataSource = new JRBeanCollectionDataSource(data);
            InputStream file = getClass().getResourceAsStream("BarangDataLaporan.jasper");
            JasperPrint jasperPrint = JasperFillManager.fillReport(file, parameter, dataSource);
            JasperViewer.viewReport(jasperPrint, false);
        }catch(JRException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_menuBarangDataActionPerformed

    private void menuPelangganDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPelangganDataActionPerformed
        HashMap parameter = new HashMap();
        Vector<HashMap> data = new Vector<HashMap>();
        int no = 0;
        
        for(Pelanggan pelanggan : pelangganModel.getData()){
            HashMap row = new HashMap();
            row.put("kode", pelanggan.getKode());
            row.put("nama", pelanggan.getNama());
            row.put("alamat", pelanggan.getAlamat());
            row.put("telepon", pelanggan.getTelepon());
            row.put("no", ++no);
            data.add(row);
        }
        
        try{
            JRDataSource dataSource = new JRBeanCollectionDataSource(data);
            InputStream file = getClass().getResourceAsStream("PelangganDataLaporan.jasper");
            JasperPrint jasperPrint = JasperFillManager.fillReport(file, parameter, dataSource);
            JasperViewer.viewReport(jasperPrint, false);
        }catch(JRException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_menuPelangganDataActionPerformed

    private void menuPenjualanDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPenjualanDataActionPerformed
        penjualanLaporan.show();
    }//GEN-LAST:event_menuPenjualanDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuBarang;
    private javax.swing.JMenuItem menuBarangData;
    private javax.swing.JMenuItem menuPelanggan;
    private javax.swing.JMenuItem menuPelangganData;
    private javax.swing.JMenuItem menuPenjualan;
    private javax.swing.JMenuItem menuPenjualanData;
    // End of variables declaration//GEN-END:variables

}
